version: '3.3'

services:

  myapp-mysql:
    image: mysql:8.0
    environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: ordersdb
       MYSQL_USER: OrdersManager
       MYSQL_PASSWORD: 1234
    ports:
      - 3307:3306
    networks:
      - production-network
    volumes:
      - mysql-database-data-volume:/var/lib/myapp-mysql

  brub-ordersdb:
    image: brub-ordersdb
    restart: on-failure
    build:
      dockerfile: ./Dockerfile
      context: .
    depends_on:
      - myapp-mysql
    ports:
      - 8080:8080
    environment:
       DATABASE_HOST: myapp-mysql
       DATABASE_USER: OrdersManager
       DATABASE_PASSWORD: 1234
       DATABASE_NAME: ordersdb
       DATABASE_PORT: 3306
    networks:
      - production-network

networks:
  production-network:
    driver: bridge

volumes:
  mysql-database-data-volume: